name: e_com
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

# Utility packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # product specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1



#Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


# State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.5.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1

#Product Specific



#--------------./ PACKAGES End -------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  #------------- LOCAL ASSETS--------------------#


  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/fonts/
    - assets/images/on_boarding_images/
    - assets/images/home_carousel/
    - assets/images/product_image/
    - assets/images/brands/
    - assets/images/user/
    - assets/product_different_images/
    - assets/icons/payment_methods/
    - assets/images/sub_categories/
    - assets/animation/


  #----------------- LOCAL FONTS-----------------#



