// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3k-91hs0uB3L6ACxN4lLLuY2qqDZ1o0c',
    appId: '1:30196510736:web:ce1f15738304f6b740da95',
    messagingSenderId: '30196510736',
    projectId: 'ecmmerceapp-40a82',
    authDomain: 'ecmmerceapp-40a82.firebaseapp.com',
    storageBucket: 'ecmmerceapp-40a82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgm8tFV2zrMTYoBQyDO9sElRiiOZih_hE',
    appId: '1:30196510736:android:f3e845136a3852b240da95',
    messagingSenderId: '30196510736',
    projectId: 'ecmmerceapp-40a82',
    storageBucket: 'ecmmerceapp-40a82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYc4iP-TOakAQYkindg2aGTXZ5OrUv44',
    appId: '1:30196510736:ios:20e99d52d67dc5ba40da95',
    messagingSenderId: '30196510736',
    projectId: 'ecmmerceapp-40a82',
    storageBucket: 'ecmmerceapp-40a82.appspot.com',
    androidClientId: '30196510736-tmsrtbnrjbn4mne3pce57801gal7l4fe.apps.googleusercontent.com',
    iosClientId: '30196510736-ledbv0m1aoma93fqhnc1nq1t066sftl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYc4iP-TOakAQYkindg2aGTXZ5OrUv44',
    appId: '1:30196510736:ios:20e99d52d67dc5ba40da95',
    messagingSenderId: '30196510736',
    projectId: 'ecmmerceapp-40a82',
    storageBucket: 'ecmmerceapp-40a82.appspot.com',
    androidClientId: '30196510736-tmsrtbnrjbn4mne3pce57801gal7l4fe.apps.googleusercontent.com',
    iosClientId: '30196510736-ledbv0m1aoma93fqhnc1nq1t066sftl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3k-91hs0uB3L6ACxN4lLLuY2qqDZ1o0c',
    appId: '1:30196510736:web:c04113b4c47c301840da95',
    messagingSenderId: '30196510736',
    projectId: 'ecmmerceapp-40a82',
    authDomain: 'ecmmerceapp-40a82.firebaseapp.com',
    storageBucket: 'ecmmerceapp-40a82.appspot.com',
  );

}